build:
	dotnet build

clean:
	dotnet clean

restore:
	dotnet restore

watch:
	dotnet watch --project src/Web/Serenity.Web.csproj run --launch-profile https

run:
	dotnet run --project src/Web/Serenity.Web.csproj --launch-profile https